# Generated by Django 3.2.7 on 2021-12-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mailing_address', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=200)),
            ],
        ),
    ]
