# Generated by Django 3.2.7 on 2021-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20211201_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewForm',
            fields=[
                ('first_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('zipcode', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
