# Generated by Django 3.2.7 on 2021-12-01 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_newform_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newform',
            name='zipcode',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')]),
        ),
    ]
