# Generated by Django 3.2.7 on 2021-12-01 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_alter_newform_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newform',
            name='zipcode',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
